name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  ci-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # local.properties 생성 (필요하다면)
    - name: Generate local.properties
      run: |
        echo "${{ secrets.LOCAL_PROPERTIES }}" > ./local.properties

    # google-services.json 생성 (필수, 제대로 동작하게 수정)
    - name: Generate google-services.json
      run: |
        echo "${{ secrets.GOOGLE_SERVICES }}" > ./app/google-services.json

    # 캐시(선택)
    - name: Gradle Caches
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # 빌드 실행
    - name: Run build
      run: ./gradlew assembleDebug --stacktrace

    # 필요하다면 추가 단계(예: test, detekt 등)
    # - name: Run Detekt
    #   run: ./gradlew detekt
